# Author: Luke Halasy <lhalasy@gmail.com>
# Idea adapted from https://github.com/tonsky/sublime-scheme-alabaster
# Colors adapted from Apple Books Light Focus Theme.

"comment" = { bg = "yellow" }
"constant" = { fg = "title_green", modifiers = ["bold"] }
"string" = { bg = "green" }

"function.declaration" = { bg = "blue" }
# "enum.declaration" = { bg = "blue" }

"ui.background" = { fg = "fg", bg = "bg" }

"ui.cursor" = { bg = "selection_anchors", fg = "bg" }
"ui.selection" = { bg = "selection_blue" }

"diagonstic" = { bg = "bg", underline = { color = "purple", style = "doubleline" } }

"diagnostic.hint" = { underline = { color = "fg", style = "double_line" } }
"diagnostic.info" = { underline = { color = "fg", style = "double_line" } }
"diagnostic.warning" = { underline = { color = "fg", style = "double_line" } }
"diagnostic.error" = { underline = { color = "fg", style = "double_line" }}

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "yellow" }
"diff.minus" = { fg = "underline_red" }

# TOML file keys
# "type" = { bg = "purple" }

[palette]
# taken from Apple Books Light Focus Theme
# bg                = "#fffcf5"
bg                = "#EEE2CB"
# fg                = "#141203"
fg                = "#32281E"

# green             = "#add396"
green             = "#A2C689"
# green             = "#C5D3BC"
# blue              = "#b4ccef"
blue              = "#A4BCC8"
# yellow            = "#f7d463"
yellow            = "#E8BC5A"
# purple            = "#d6c0ef"
purple            = "#C0ADC5"
# pink              = "#f1b2bc"
pink              = "#45753E"

underline_red     = "#ec3824"

# selection_blue    = "#d0dff2"
selection_blue    = "#C2CBCA"
# selection_anchors = "#588fec"
selection_anchors = "#5181C4"
# title_green       = "#4b8248"
title_green       = "#45753E"
title_red         = "#da5938"
