# Author: Luke Halasy <lhalasy@gmail.com>
# Idea adapted from https://github.com/tonsky/sublime-scheme-alabaster
# Colors adapted from Apple Books Light Calm Theme.
# TODO: rstrst
# FIXME: 

"comment" = { bg = "yellow" }
"constant" = { fg = "title_green", modifiers = ["bold"] }
"string" = { bg = "green" }
"punctuation.delimiter" = { fg = "fg_bg_average" }
"operator" = { fg = "fg_bg_average" }
# "keyword" = { modifiers = ["dim"] }


"function.declaration" = { bg = "blue" }
# "enum.declaration" = { bg = "blue" }

"ui.background" = { fg = "fg", bg = "bg" }

"ui.cursor" = { bg = "fg", fg = "bg" }
"ui.selection" = { bg = "selection_blue" }

"diagonstic" = { bg = "bg", underline = { color = "purple", style = "doubleline" } }

"diagnostic.hint" = { underline = { color = "#000000", style = "double_line" } }
"diagnostic.info" = { underline = { color = "#000000", style = "double_line" } }
"diagnostic.warning" = { underline = { color = "#000000", style = "double_line" } }
"diagnostic.error" = { underline = { color = "#000000", style = "double_line" }}

"hint" = { bg = "blue", fg = "fg", modifiers = ["bold"]}
"info" = { bg = "blue", fg = "fg", modifiers = ["bold"]}
"error" = { bg = "pink", fg = "fg", modifiers = ["bold"] }
"warning" = { fg = "underline_yellow" }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "fg" }
"diff.minus" = { fg = "underline_red" }

# TOML file keys
# "type" = { bg = "purple" }

[palette]
bg                = "#EEE2CB"
fg                = "#111D34"
fg_bg_average     = "#7F7F7F"

green             = "#A2C689"
blue              = "#A4BCC8"
yellow            = "#E8BC5A"
purple            = "#C0ADC5"
pink              = "#DD9FAA"

underline_red     = "#ec3824"
underline_orange     = "#EC9023"

selection_blue    = "#C2CBCA"
selection_anchors = "#5181C4"

title_green       = "#45753E"
title_red         = "#da5938"
