# Author: Luke Halasy <lhalasy@gmail.com>
# Adapted from https://github.com/tonsky/sublime-scheme-alabaster

"comment"               = { bg = "#362A23", modifiers = ["italic"]}
# "constant"              = { fg = "title_green",  modifiers = ["bold"] }
"string"                = { fg = "#AC766E" }
"punctuation.delimiter" = { fg = "fg_bg_average" }
"operator"              = { fg = "fg_bg_average" }


# "function.declaration" = { fg = "#6E95AC" }
"function.declaration" = { fg = "#597A8C" }

"ui.background" = { fg = "fg", bg = "bg" }

# "ui.cursor" = { bg = "dark_brown", fg = "bg" }
"ui.selection" = { bg = "brown", fg = "fg" }

# "diagnostic" = { bg = "bg", underline = { color = "purple", style = "doubleline" } }

# "diagnostic.hint"    = { underline = { color = "fg", style = "double_line" } }
# "diagnostic.info"    = { underline = { color = "fg", style = "double_line" } }
# "diagnostic.warning" = { underline = { color = "fg", style = "double_line" } }
# "diagnostic.error"   = { underline = { color = "fg", style = "double_line" }}

# "hint" = { bg = "blue", fg = "fg", modifiers = ["bold"]}
# "info" = { bg = "blue", fg = "fg", modifiers = ["bold"]}
# "error" = { bg = "pink", fg = "fg", modifiers = ["bold"] }
# "warning" = { fg = "underline_darker_beige" }

# "diff.plus" = { fg = "dark_brown" }
# "diff.delta" = { fg = "dark_brown" }
# "diff.minus" = { fg = "underline_red" }

# "ui.help" = { fg = "fg", bg = "brown" }
# "ui.popup" = { fg = "fg", bg = "darker_beige" }
# "ui.window" = { fg = "fg", bg = "darker_beige" }

# "ui.menu" = { fg = "fg", bg = "darker_beige" }
# "ui.menu.selected" = { bg = "#BCA787", fg = "fg" }
# "ui.menu.scroll" = { fg = "fg", bg = "bg" }



[palette]
bg                = "#1E1914"
fg                = "#B59F8A"
fg_bg_average     = "#695C4F"

green             = "#DBDBBB"
blue              = "#D2D4CA"
darker_beige      = "#D8C9B0"
brown             = "#BCA787"
dark_brown        = "#4B361B"
purple            = "#DDCEC9"
pink              = "#DD9FAA"

underline_red     = "#ec3824"
underline_orange  = "#EC9023"

selection_blue    = "#C2CBCA"
selection_anchors = "#5181C4"

title_green       = "#45753E"
title_red         = "#da5938"
